stages:
 - mavenbuild
 - maventest
 - mavendeploy
 - androidbuild
 - androidtest

maven-build:  
  stage: mavenbuild
  tags:
    - springboot_tag                      
  script:
    - cd Backend                   
    - mvn package

maven-test:
  stage: maventest
  tags:
    - springboot_tag
  script:
    - cd Backend
    - mvn test
  artifacts:
    paths:
      - Backend/target/*.jar

maven-deploy:
  stage: mavendeploy
  tags:
   - springboot_tag
  only:
   - main 
  script:
    - cd Backend
    - mvn package
    - sudo mv target/*.jar /target/web-demo.jar
    - sudo systemctl stop system-web-demo
    - sudo systemctl start system-web-demo

android-build:
  image: gjandres/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle 
    - chmod +x ./Frontend/gradlew
  tags:
    - android_tag
  script:
    - cd Frontend
    - ./gradlew build
  artifacts:
    paths:
      - Android_test/app/build/outputs/

android-test:
  image: gjandres/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/gradlew
  tags:
    - android_tag
  script:
    - cd Frontend
    - ./gradlew test
